//GET http://localhost:3000/api/empleados/
//GET http://localhost:3000/api/informacion-consultoria/
//GET http://localhost:3000/api/usuarios/

//GET http://localhost:3000/api/usuarios/6533cb9bcfcec1c25a30b382
//GET http://localhost:3000/api/pagos-facturas/
//GET http://localhost:3000/api/pagos-facturas/filtrar?monto=1500
//GET http://localhost:3000/api/informacion-consultoria/filtrar?cliente=Ayelin
//DELETE http://localhost:3000/api/pagos-facturas/65616f40d3a1c7134345f45f
POST http://localhost:3000/api/informacion-consultoria/ HTTP/1.1
Content-Type: application/json

{
    "cliente": "Fiorella",
    "tipo_servicio": "Consultoría en ciberseguridad",
    "fecha": "2023-11-29T22:23:43.000Z",
    "pregunta_frecuente": "Cuánto es el costo?",
    "estado": "pendiente"
}
